CREATE TABLE `feels` (
	`feel_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`ip_hash` binary(20) NOT NULL,
	`feel` tinyint(1) NOT NULL,
	`time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`latitude` float NOT NULL,
	`longitude` float NOT NULL,
	`sphere_x` float NOT NULL,
	`sphere_y` float NOT NULL,
	`sphere_z` float NOT NULL,
	`location_id` int(10) UNSIGNED NOT NULL,
	`symptom_bluish_lips` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_chest_pressure` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_chills` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_congestion` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_constipation` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_cough` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_diarrhea` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_difficulty_breathing` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_dry_cough` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_dry_mouth` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_ear_ache` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_fever` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_flatulence` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_head_congestion` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_headaches` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_increase_in_appetite` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_itchy` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_itchy_bottom` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_joint_aches` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_joint_soreness` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_leg_cramps` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_loss_of_appetite` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_loss_of_smell_or_taste` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_mucle_soreness` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_muscel_aches` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_nosebleed` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_runny_nose` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_sensitivity_to_light` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_skin_blisters` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_skin_rash` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_sneezing` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_sore_throat` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_swollen_lymph_nodes` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_tiredness` tinyint(1) NOT NULL DEFAULT '0',
	`symptom_wet_cough` tinyint(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`feel_id`),
	UNIQUE KEY `ip_hash` (`ip_hash`);
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `locations` (
	`location_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`country` char(2) COLLATE utf8_unicode_ci NOT NULL,
	`state_prov` text COLLATE utf8_unicode_ci NOT NULL,
	`city` text COLLATE utf8_unicode_ci NOT NULL,
	`zipcode` text COLLATE utf8_unicode_ci NOT NULL,
	`district` text COLLATE utf8_unicode_ci NOT NULL,
	PRIMARY KEY (`location_id`);
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `location_cache` (
	`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`ip_hash` binary(20) NOT NULL,
	`time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`latitude` float NOT NULL,
	`longitude` float NOT NULL,
	`sphere_x` float NOT NULL,
	`sphere_y` float NOT NULL,
	`sphere_z` float NOT NULL,
	`location_id` int(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `ip_hash` (`ip_hash`);
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

